version: 2.1

setup: true

parameters:
  b64diff:
    type: string
    default: ""

orbs:
  continuation: sandbox/continuation@0.0.3
  local_tests:
    commands:
      patch:
        parameters:
          parameter_name:
            type: string
          config_file:
            type: string
        steps:
          - run:
              name: Apply the patch
              command: |
                        yq e -i '.parameters.b64diff = {"type": string, "default": ""}' << parameters.config_file >>
                        yq e '.jobs | select(.*.steps.[] == "checkout") | keys' << parameters.config_file >> |
                          awk '{print $2}' |
                          xargs -n 1 -I {} yq e -i 'del(.jobs.{}.steps.[0]) | .jobs.{}.steps = ["checkout", {"run": {"command": "echo \"\<\< parameters.branch_data \>\>\" | base64 -d | patch -p0", "name": "patching"}}] + .jobs.{}.steps' << parameters.config_file >>

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: sudo apt-get install awk
      - run: sudo wget https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_386 -O /usr/bin/yq && sudo chmod 755 /usr/bin/yq
      - local_tests/patch:
          parameter_name: "b64diff"
          config_file: .circleci/continue_config.yml
      - run: cat .circleci/continue_config.yml
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml
          parameters: '{"b64diff": "<< pipeline.parameters.b64diff >>"}'

workflows:
  setup:
    jobs:
      - setup
