version: 2.1

setup: true

parameters:
  b64diff:
    type: string
    default: ""

orbs:
  continuation: sandbox/continuation@0.0.3
  local_tests:
    commands:
      patch:
        parameters:
          config_file:
            type: string
        steps:
          - run:
              name: Apply the patch
              command: yq e '.jobs | select(.*.steps.[] == "checkout") | keys' << parameters.config_file >> \
                | awk '{print $2}' \
                | xargs -n 1 -I {} \
                  yq e -i '.jobs.{}.steps.[1] |= "echo << pipeline.parameters.b64diff >> | base64 -d | patch"' << parameters.config_file >>

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: sudo apt-get install yq
      - local_tests/patch:
          config_file: .circleci/continue_config.yml
      - continuation/continue:
          configuration_path: .circleci/continue_config.yml

workflows:
  setup:
    jobs:
      - setup
