# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

parameters:
  b64diff:
    type: string
    default: ""

orbs:
  maven: circleci/maven@0.0.9

executors:
  jdk:
    docker:
      - image: 'circleci/openjdk:8u212-jdk-stretch'
jobs:
 foo:
   docker:
     - image: circleci/openjdk:8-jdk
   steps:
     - checkout
     - run: echo "<< pipeline.parameters.b64diff >>" | base64 -d > diff.patch
     - run: patch < diff.patch
     - run:
         name: Test
         command: cat fizz.buzz
workflows:
  maven_test:
    jobs:
      - foo
